In [2]:
import torch

In [3]:
import torchvision

In [5]:
print(torch.cuda.is_available())

False


In [6]:
#this is a 1-D Tensor
a=torch.tensor([2,2,1])
print(a)

tensor([ 2,  2,  1])


In [7]:
#This is a 2-D Tensor
b=torch.tensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
print(b)

tensor([[ 2,  1,  4],
        [ 3,  5,  4],
        [ 1,  2,  0],
        [ 4,  3,  2]])


In [8]:
#The size of the tensors
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [9]:
#Get the height/number of rows of b
print(b.shape[0])

4


In [10]:
c=torch.FloatTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
#or we can do
#c=torch.ensor([2,2,1,dtype=torch.float])

In [11]:
d=torch.DoubleTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])
#or we can do
#d=torch.tensor([2,2,1],dtype=torch.double)

In [12]:
print(c)
print(c.dtype)

tensor([[ 2.,  1.,  4.],
        [ 3.,  5.,  4.],
        [ 1.,  2.,  0.],
        [ 4.,  3.,  2.]])
torch.float32


In [13]:
print(d)
print(d.dtype)

tensor([[ 2.,  1.,  4.],
        [ 3.,  5.,  4.],
        [ 1.,  2.,  0.],
        [ 4.,  3.,  2.]], dtype=torch.float64)
torch.float64


In [14]:
print(c.mean())
#求取均值

tensor(2.5833)


In [15]:
print(d.mean())

tensor(2.5833, dtype=torch.float64)


In [16]:
print(c.std())
#求标准差

tensor(1.5050)


In [17]:
print(d.std())

tensor(1.5050, dtype=torch.float64)


In [19]:
#Reshape b
#Note:If one of the dimensions is -1, its size can be inferred
print(b.view(-1,1))
print(b.view(12))
print(b.view(-1,4))
print(b.view(3,4))

tensor([[ 2],
        [ 1],
        [ 4],
        [ 3],
        [ 5],
        [ 4],
        [ 1],
        [ 2],
        [ 0],
        [ 4],
        [ 3],
        [ 2]])
tensor([ 2,  1,  4,  3,  5,  4,  1,  2,  0,  4,  3,  2])
tensor([[ 2,  1,  4,  3],
        [ 5,  4,  1,  2],
        [ 0,  4,  3,  2]])
tensor([[ 2,  1,  4,  3],
        [ 5,  4,  1,  2],
        [ 0,  4,  3,  2]])


In [21]:
#Assign b a new shape
b=b.view(1,-1)
print(b)
print(b.shape)
#We can even reshape 3D tensors
print('\n')
#Create a 3D Tensor with 2 channels, 3 rows and 4 columns (channels, rows, columns)
#torch.randn(*sizes, out=None) → Tensor
#返回一个张量，包含了从标准正态分布（均值为0，方差为1，即高斯白噪声）中抽取的一组随机数。
#张量的形状由参数sizes定义。
three_dim=torch.randn(2,3,4)
print('\n')
print(three_dim)
print(three_dim.view(2,12)) # Reshape to 2 rows, 12 columns
print(three_dim.view(2,-1))

tensor([[ 2,  1,  4,  3,  5,  4,  1,  2,  0,  4,  3,  2]])
torch.Size([1, 12])




tensor([[[ 1.7081, -0.6614, -2.0940, -1.3346],
         [ 0.8651, -0.7766, -0.1780,  1.0173],
         [ 0.5499,  0.4557,  1.1252, -0.1963]],

        [[ 0.0927, -1.7965,  0.5281,  2.5165],
         [-0.4610,  0.1437,  1.4804,  0.3369],
         [-0.9207, -0.8173, -0.0567,  0.8351]]])
tensor([[ 1.7081, -0.6614, -2.0940, -1.3346,  0.8651, -0.7766, -0.1780,
          1.0173,  0.5499,  0.4557,  1.1252, -0.1963],
        [ 0.0927, -1.7965,  0.5281,  2.5165, -0.4610,  0.1437,  1.4804,
          0.3369, -0.9207, -0.8173, -0.0567,  0.8351]])
tensor([[ 1.7081, -0.6614, -2.0940, -1.3346,  0.8651, -0.7766, -0.1780,
          1.0173,  0.5499,  0.4557,  1.1252, -0.1963],
        [ 0.0927, -1.7965,  0.5281,  2.5165, -0.4610,  0.1437,  1.4804,
          0.3369, -0.9207, -0.8173, -0.0567,  0.8351]])


In [22]:
#Create a matric with random numbers between 0 and 1
#torch.rand(*sizes, out=None) → Tensor
#返回一个张量，包含了从区间[0, 1)的均匀分布中抽取的一组随机数。
#张量的形状由参数sizes定义。
r=torch.rand(4,4)
print(r)

tensor([[ 0.1506,  0.4688,  0.6062,  0.1516],
        [ 0.8300,  0.8133,  0.6374,  0.8972],
        [ 0.5959,  0.8155,  0.6079,  0.6395],
        [ 0.8541,  0.6399,  0.5635,  0.7044]])


In [23]:
#Create an matrix with random numbers taken from a normal distribution with
#mean 0 and variance 1
r2=torch.randn(4,4)
print(r2)
print(r2.dtype)

tensor([[ 0.1522, -0.5220, -0.1074,  0.1575],
        [-0.6944,  0.4178, -0.3124, -1.5074],
        [-1.2755,  1.1937, -0.3954,  0.8207],
        [-1.4138,  0.3622, -0.9647,  0.1603]])
torch.float32


In [26]:
#Create an array of 5 random integers from values between 6 and 9(exclusize of 10)
in_array=torch.randint(6,10,(5,))
print(in_array)
print(in_array.dtype)

tensor([ 6.,  8.,  6.,  9.,  8.])
torch.float32


In [28]:
#Create a 2-D array (or matrix) of size 3*3 filled with random integers
#between 6 and 9 (exclusive of 10)
in_array2=torch.randint(6,10,(3,3))
print(in_array2)

tensor([[ 6.,  7.,  9.],
        [ 9.,  9.,  6.],
        [ 7.,  8.,  7.]])


In [29]:
#Get the number of elements in in_array
print(torch.numel(in_array))
#Get the number of elements in in_array_2
print(torch.numel(in_array2))

5
9


In [30]:
#Construct a 3*3 matrix of zero and of dtype long:
z=torch.zeros(3,3,dtype=torch.long)
print(z)
#Construct a 3*3 matrix of ones
o=torch.ones(3,3)
#pytorch的自动类型是float
print(o)
print(o.dtype)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])
tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])
torch.float32


In [32]:
#建一个和r2同尺寸的符合正太分布的随机tensor
r2_like=torch.randn_like(r2,dtype=torch.double)
print(r2_like)

tensor([[-0.3689, -1.1523,  1.3534,  0.5507],
        [ 1.2853, -0.9601, -0.5172,  0.0778],
        [ 0.5381, -3.3371,  0.2156, -0.8474],
        [-1.0208,  0.9740,  0.7008, -0.3437]], dtype=torch.float64)


In [33]:
#Add two tensors, make sure they are the same size and data type
add_result=torch.add(r,r2)
print(add_result)

tensor([[ 0.3027, -0.0532,  0.4988,  0.3091],
        [ 0.1356,  1.2312,  0.3249, -0.6102],
        [-0.6796,  2.0091,  0.2125,  1.4602],
        [-0.5597,  1.0021, -0.4013,  0.8647]])


In [34]:
#In-place addition (change the value of r2)
#加下划线的add会直接进行替换，将r2和r的值的和赋值给了r2
r2.add_(r)
print(r2)

tensor([[ 0.3027, -0.0532,  0.4988,  0.3091],
        [ 0.1356,  1.2312,  0.3249, -0.6102],
        [-0.6796,  2.0091,  0.2125,  1.4602],
        [-0.5597,  1.0021, -0.4013,  0.8647]])


In [36]:
print(r2[:,1])
print(r2[:,:2])
print(r2[:3,:])
num_ten=r2[2,3]
print(num_ten)#这个出来的结果是一个tensor
print(num_ten.item())#这样可以将结果从tensor中拿出来
print(r2[2,:])

tensor([-0.0532,  1.2312,  2.0091,  1.0021])
tensor([[ 0.3027, -0.0532],
        [ 0.1356,  1.2312],
        [-0.6796,  2.0091],
        [-0.5597,  1.0021]])
tensor([[ 0.3027, -0.0532,  0.4988,  0.3091],
        [ 0.1356,  1.2312,  0.3249, -0.6102],
        [-0.6796,  2.0091,  0.2125,  1.4602]])
tensor(1.4602)
1.460208535194397
tensor([-0.6796,  2.0091,  0.2125,  1.4602])
